Repository dpaul93/Group-17-Project-2, pull requests merged in 2024-03, with the labels that each got.

#7 Feature/bootstrap
  package-lock.json
  package.json
Labels: enhancement

#4 added socket.io
  package-lock.json
  package.json
Labels: enhancement

#10 added bootstrap imports to main
  src/main.jsx
Labels: bug, enhancement

#15 created chat page component to hold to the other smaller components
  src/components/chat-page/ChatPage.jsx
Labels: enhancement

#17 added stylised landing page
  src/App.css
  src/components/Home.jsx
  src/styles/Home.css
Labels: enhancement

#33 fixed landing page so than empty profile is not shown
  src/components/Home.jsx
Labels: bug

#42 added basic readme file containing basic information about the projec…
  README.md
Labels: documentation

#55 edited landing page with logo and added favicon
  index.html
  src/components/Home.jsx
  src/image/Logo3.png
  src/image/favicon.png
  src/image/yappa_logo.png
  src/image/yappa_logo_sml.png
  src/styles/Home.css
Labels: enhancement

#60 Branding
  src/App.css
  src/components/chat-bar/ChatBar.jsx
  src/components/chat-body/ChatBody.jsx
Labels: enhancement
